name: Gatsby Publish

on:
  push:
    branches:
      - main # 推送到 main 分支时触发
  schedule:
    - cron: '0 0 * * *'  # 每天的UTC时间00:00运行一次

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}